# Numpy

### Numpy array

In [1]:
# 리스트와 넘파이 어레이 속도 비결
import numpy as np
np_arr = np.arange(100000)
nu_list = [i for i in range(100000)]

In [2]:
%%time
for i in range(100):
    sum(nu_list)

Wall time: 164 ms


In [17]:
%%time
for i in range(100):
    sum = 0
    np.sum(np_arr)

Wall time: 5.99 ms


In [19]:
ar = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
type(ar)

numpy.ndarray

In [21]:
ar.shape # 이게 뭔지 알아보기

(10,)

In [22]:
data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [23]:
answer = []
for di in data:
    answer.append(2 * di)
answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [28]:
al = [2 * i for i in range(1,11)]
al

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [29]:
2 * ar # Numpy이는 값의 2배를 하지만, list는 2번 반복한다.

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [30]:
al * 2 # Numpy이는 값의 2배를 하지만, list는 2번 반복한다.

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [31]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

In [32]:
2 * a + b

array([12, 24, 36])

In [33]:
a == 2

array([False,  True, False])

In [34]:
b > 15

array([False,  True,  True])

In [35]:
(a == 2) & (b > 10)

array([False,  True, False])

### 2차원 배열

In [36]:
c = np.array([[0, 1, 2], [3, 4, 5]])  # 2 x 3 array
c

array([[0, 1, 2],
       [3, 4, 5]])

In [37]:
c.shape # 행 열이 갯수 표현

(2, 3)

In [39]:
len(c), len(c[0]) # 행의 갯수 - len(c) / 열의 갯수 - len(c[0])

(2, 3)

In [42]:
np.arange(10, 90, 10).reshape(2, -1)

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [6]:
d = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]],
              [[11, 12, 13, 14],
               [15, 16, 17, 18],
               [19, 20, 21, 22]]])   # 2 x 3 x 4 array
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

In [7]:
d.shape

(2, 3, 4)

In [8]:
d.shape, d.ndim  # shape - 행열 수(차원 수에 따라 생김), ndim - 차원 수

((2, 3, 4), 3)

배열의 인덱싱

In [10]:
a = np.array([0, 1, 2, 3, 4])
a[2]

2

In [11]:
a[-1]

4

In [13]:
a = np.array([[0, 1, 2],[3, 4, 5]])
a[1, 0]

3

### 배열 슬라이싱

In [14]:
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [15]:
a[:, 1:3] # 행열 순서로 뽑아 낸다.

array([[1, 2],
       [5, 6]])

In [24]:
m = np.array([[0,  1,  2,  3,  4],
            [5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])

In [25]:
# 행렬에서 값 7 을 인덱싱한다.
m[1, 2]

7

In [26]:
# 이 행렬에서 값 14 을 인덱싱한다.
m[2, 4]

14

In [27]:
# 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
m[1, 1:3]

array([6, 7])

In [28]:
# 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
m[1:3, 2]

array([ 7, 12])

In [29]:
# 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.

m[0:2, 3:5]

array([[3, 4],
       [8, 9]])

In [30]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True,
               False, True, False, True, False])
a[idx]

array([0, 2, 4, 6, 8])

In [32]:
a % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [33]:
a[a % 2 == 0]

array([0, 2, 4, 6, 8])

In [34]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 2, 4, 6, 8])
a[idx]

array([11, 33, 55, 77, 99])

In [35]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [37]:
a[:, [True, False, False, True]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [38]:
a[[2, 0, 1], :]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [39]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [52]:
# 이 배열에서 3의 배수를 찾아라.
y = x[x % 3 == 0]
y

array([ 3,  6,  9, 12, 15, 18])

In [53]:
# 이 배열에서 4로 나누면 1이 남는 수를 찾아라.
z = x[x % 4 == 1]

In [56]:
print(y+z)

ValueError: operands could not be broadcast together with shapes (6,) (5,) 