# 배열의 연산

백터화 연산

In [2]:
import numpy as np

In [2]:
x = np.arange(1, 10001)
y = np.arange(10001, 20001)

In [3]:
%%time
z = np.zeros_like(x)
for i in range(10000):
    z[i] = x[i] + y[i]

Wall time: 6 ms


In [4]:
%%time
z = x + y

Wall time: 999 µs


In [5]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
a == b

array([False,  True, False,  True])

In [6]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = np.array([1, 2, 3, 4])

In [7]:
np.all(a == b)

False

In [8]:
np.all(a == c)

True

In [10]:
a = np.arange(1,11)
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [11]:
np.log10(a)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ])

### 스칼라와 벡터/행렬의 곱셉

In [12]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
100 * x

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [14]:
x = np.arange(12).reshape(3, 4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
100 * x

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

### 브로드 캐스팅

In [16]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [17]:
y = np.ones_like(x)
y

array([1, 1, 1, 1, 1])

In [18]:
x + y

array([1, 2, 3, 4, 5])

In [19]:
x + 1

array([1, 2, 3, 4, 5])

In [6]:
x = np.array([[1, 1], [2, 2]])
x

array([[1, 1],
       [2, 2]])

In [7]:
np.sum(x)

6

In [9]:
np.sum(x, axis=0)  # axis = 0 이면 열, axis = 1이면 행 합을 구하는것을 의미

array([3, 3])

In [10]:
np.sum(x, axis=1) 

array([2, 4])

In [27]:
x = np.linspace(1.0, 10.0, 30).reshape(5, 6)

In [28]:
x

array([[ 1.        ,  1.31034483,  1.62068966,  1.93103448,  2.24137931,
         2.55172414],
       [ 2.86206897,  3.17241379,  3.48275862,  3.79310345,  4.10344828,
         4.4137931 ],
       [ 4.72413793,  5.03448276,  5.34482759,  5.65517241,  5.96551724,
         6.27586207],
       [ 6.5862069 ,  6.89655172,  7.20689655,  7.51724138,  7.82758621,
         8.13793103],
       [ 8.44827586,  8.75862069,  9.06896552,  9.37931034,  9.68965517,
        10.        ]])

In [40]:
# 전체의 최댓값
x.max()

10.0

In [41]:
# 각 행의 합
x.sum(axis=1)

array([10.65517241, 21.82758621, 33.        , 44.17241379, 55.34482759])

In [42]:
# 각 행의 최댓값
x.argmax(axis=1)

array([5, 5, 5, 5, 5], dtype=int64)

In [43]:
# 각 열의 평균
x.mean(axis=0)

array([4.72413793, 5.03448276, 5.34482759, 5.65517241, 5.96551724,
       6.27586207])

In [44]:
# 각 열의 최솟값
x.min(axis=0)

array([1.        , 1.31034483, 1.62068966, 1.93103448, 2.24137931,
       2.55172414])

### 정렬

In [45]:
a = np.array([[4,  3,  5,  7],
              [1, 12, 11,  9],
              [2, 15,  1, 14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [46]:
np.sort(a)

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [47]:
np.sort(a, axis=1)

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [48]:
np.sort(a, axis=0)

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [49]:
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [50]:
a.sort() # np.sort(a)는 a위치를 변경시키지 않지만 a.sort()는 a위치를 변경시킴

In [51]:
a

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])