# 난수 발생과 카운팅

In [1]:
import numpy as np

### 시드 설정하기

In [2]:
np.random.rand(5)

array([0.59606741, 0.02469927, 0.38751888, 0.0548237 , 0.44914109])

In [4]:
np.random.rand(5)

array([0.29632536, 0.39634786, 0.60728822, 0.09247517, 0.98300058])

In [5]:
np.random.seed(2020)    # 재사용을 할 때는 seed(변수)를 넣어줘서 고정 가능
np.random.rand(5)

array([0.98627683, 0.87339195, 0.50974552, 0.27183571, 0.33691873])

In [6]:
np.random.seed(2020)
np.random.rand(5)

array([0.98627683, 0.87339195, 0.50974552, 0.27183571, 0.33691873])

### 데이터 순서 바꾸기

In [7]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.random.shuffle(x) # 셔플을 사용하고 난 뒤 값이 변경되므로 주의해야한다.
x

array([5, 7, 6, 4, 3, 1, 2, 8, 9, 0])

### 데이터 샘플링

In [9]:
# True = 복원 추출(뽑은 데이터를 다시 뽑을 수 있음), False = 비복원 추출
np.random.choice(5, 5, replace=False)

array([4, 0, 1, 2, 3])

In [11]:
# True = 복원 추출(뽑은 데이터를 다시 뽑을 수 있음), False = 비복원 추출
np.random.choice(5, 5, replace=True)

array([4, 1, 1, 2, 1])

In [10]:
np.random.choice(5, 3, replace=False) 

array([1, 2, 3])

In [12]:
np.random.choice(5, 10)

array([2, 4, 4, 2, 3, 4, 1, 4, 1, 3])

In [14]:
np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0]) # p는 확률을 의미

array([3, 3, 3, 3, 3, 0, 2, 3, 3, 2])

### 난수 생성

In [15]:
np.random.rand(5)

array([0.42565598, 0.51342021, 0.26937759, 0.59902002, 0.22017395])

In [16]:
np.random.randn(10)

array([-0.20832874, -0.09186351,  0.70268816,  0.10365506,  0.62123638,
        0.95411497,  2.03781352, -0.48445122,  0.2071549 ,  1.64424216])

In [17]:
np.random.randint(10, size=10)

array([6, 9, 5, 2, 4, 3, 0, 9, 8, 2])

In [18]:
np.random.randint(10, 20, size=10)

array([10, 16, 17, 11, 17, 12, 15, 19, 16, 17])

In [39]:
# 연습문제 3.5.2
prices  = []
price = 10000
for i in range(250):
    tmp = price * (1+ np.random.randn(1)/100.)
    price = tmp[0]
    prices.append(price)
prices[:10]

[10073.153530012345,
 10101.384367580273,
 9999.943553075986,
 10026.663027847093,
 9900.01732515773,
 9837.99633416089,
 9752.069193516154,
 9880.830577829394,
 9811.021951129913,
 9943.48530087656]

### 정수 데이터 카운팅

In [40]:
np.unique([11, 11, 2, 2, 34, 34]) # 중복된 값은 제거 후 결과값 출력

array([ 2, 11, 34])

In [41]:
a = np.array(['a', 'b', 'b', 'c', 'a'])
index, count = np.unique(a, return_counts=True)

In [44]:
print(index, count)

['a' 'b' 'c'] [2 2 1]


In [45]:
np.bincount([1, 1, 2, 2, 2, 3], minlength=6) # 1이 2개, 2가 3개, 3이 1개

array([0, 2, 3, 1, 0, 0], dtype=int64)