# 벡터와 벡터의 곱셈

In [30]:
import numpy as np

In [5]:
x = np.arange(1, 4).reshape(3, 1)
x

array([[1],
       [2],
       [3]])

In [6]:
y = np.arange(4, 7).reshape(3, 1)
y

array([[4],
       [5],
       [6]])

In [7]:
x.shape, y.shape

((3, 1), (3, 1))

In [8]:
x.T.shape

(1, 3)

In [10]:
z = x.T @ y
z

array([[32]])

In [11]:
z.shape

(1, 1)

In [12]:
z[0, 0]

32

In [13]:
np.dot(x.T, y) # 벡터의 내적

array([[32]])

In [16]:
x = np.arange(1,7).reshape(2,3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
x @ x.T

array([[14, 32],
       [32, 77]])

In [37]:
def mat_mul(x, y):
    z = np.zeros((len(x), len(y[0])))
    if len(x[0]) != len(y):
        return z
    for i in range(len(x)):
        for m in range(len(y[0])):
            val = 0
            for k in range(len(x[0])):
                val += x[i, k] * y[k, m]
            z[i, m] = val
    return z

In [38]:
x = np.arange(1, 7).reshape(3, 2)

In [39]:
y = x.T 

In [40]:
z = mat_mul(10, 20)
z

TypeError: object of type 'int' has no len()

In [32]:
np.dot(x, y)

array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]])

In [41]:
A = 1000000
B = 800000
C = 500000
p = np.array([[1000000], [800000], [500000]])
n = np.array([[3], [4], [5]])

In [46]:
money = n.T @ p
money

array([[8700000]])

In [49]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1, 2], [3, 4], [5, 6]])
C = A @ B
C

array([[22, 28],
       [49, 64]])

In [50]:
D = B @ A 
D

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [51]:
A = np.array([[1, 2, 3]])
B = np.array([[4, 7], [5, 8], [6, 9]])

# A @ B 는 (32, 50) , B @ A는 계산 불가능

In [52]:
C = A @ B
C

array([[32, 50]])

In [53]:
D = B @ A
D

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 2)

In [54]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [55]:
C = A @ B
C
# A @ B [[19, 22], [43, 50]] 둘다 계산 가능하지만, 결과값은 다르다.
# B @ A [[23, 34], [31, 46]]

array([[19, 22],
       [43, 50]])

In [56]:
D = B @ A
D

array([[23, 34],
       [31, 46]])

In [58]:
A = np.array([[1, 2], [3, 4], [5, 6]])

In [60]:
C = A @ A.T
D = A.T @ A
# 2 x 2 혹은 3 x 3행렬이 된다(정방행렬이 된다.)

In [61]:
C

array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]])

In [62]:
D

array([[35, 44],
       [44, 56]])

In [63]:
A = np.array([[1, 2, 3]])

In [64]:
C = A @ A.T
D = A.T @ A
C
# A @ A.T는 스칼라(14)이고, A.T @ A 는 3 x 3 정방행렬이다.

array([[14]])

In [65]:
D

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])