# Numpy 연습문제 풀이

In [2]:
import numpy as np

1. 길이가 10인 0-벡터를 만드세요. 

In [4]:
x =  np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

2. 길이가 10이며 다섯번째 원소만 1이고 나머지 원소는 모두 0인 벡터를 만드세요.

In [80]:
x = np.hstack([1 if i == 4 else 0 for i in range(10)])
x

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

3. 10부터 49까지의 값을 가지는 벡터를 만드세요.

In [59]:
x = np.arange(10, 50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. 위(3번) 벡터의 순서를 바꾸세요.

In [60]:
y = x[::-1]
y

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

5. 0부터 8까지의 값을 가지는 3x3 행렬을 만드세요.

In [61]:
x = np.arange(0,9).reshape(3, 3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

6. 벡터 \[1,2,0,0,4,0\]에서 원소의 값이 0이 아닌 원소만 선택한 벡터를 만드세요.

In [86]:
y = np.hstack([x[i] for i in range(len(x)) if x[i] != 0])
y

array([1, 2, 4])

7. 3x3 단위 행렬(identity matrix)을 만드세요.

In [101]:
x = np.array([[1 if i == k else 0 for i in range(3)] for k in range(3) ])
x

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

8. 난수 원소를 가지는 3x3 행렬을 만드세요

In [64]:
x = np.random.rand(9).reshape(3, 3)
x

array([[0.18245962, 0.49538087, 0.63422166],
       [0.28144776, 0.76127973, 0.78892904],
       [0.66161535, 0.99740255, 0.96149642]])

9. 위 (8번)에서 만든 난수 행렬에서 최대값/ 최소값 원소를 찾으세요.

In [65]:
print('최대값 :', x.max())
print('최소값 :', x.min())

최대값 : 0.9974025537724078
최소값 : 0.18245961906235564


10. 위 (8번)에서 만든 난수 행렬에서 행 평균, 열 평균을 계산하세요.

In [66]:
print('행 평균 :', x.mean(axis=1))
print('열 평균 :', x.mean(axis=0))

행 평균 : [0.43735405 0.61055218 0.87350477]
열 평균 : [0.37517424 0.75135438 0.79488237]
